config/routes.rb
Rails.application.routes.draw do
  resources :categories
  resources :events do 
    resources :likes
    resources :registrations
  end
  resources :contacts, only: [:new, :create]
  root to: 'events#index'
  get 'events/filter/:filter', to: 'events#index',as: :filter
  resources :users
  get 'signup', to: 'users#new'

  resource :session , only: [:new, :create, :destroy]
end

app/views/shared/_errors.html.erb
 <% if object.errors.any?%>
    <div class="errors">
       <h4>
       <%= pluralize(object.errors.size, "error")%> occured
       </h4>
       <ul>
          <% object.errors.full_messages.each do |message|%>
          <li><%=message%></li>
          <%end%>
       </ul>
    </div>
 <%end%>

app/views/shared/_flash.html.erb
<div class="flash_wrapper">
    <%if flash[:notice]%>
      <div class="alert alert-success alert-dismissible fade show" role="alert">
          <%=flash[:notice]%>
          <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
    <%end%>

    <%if flash[:alert]%>
      <div class="alert alert-danger alert-dismissible fade show" role="alert">
          <%=flash[:alert]%>
          <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
    <%end%>
  </div>

app/views/shared/_footer.html.erb
<section class="foot bg-dark">
  <div class="container">
      <div class="footer py-4 text-white text-center">
          Made by Sassltd <a href="">Sassltd.com</a>
      </div>
  </div>
</section>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container">
    <a class="navbar-brand" href="/">Navbar</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
      <% if current_user_admin?%>
          <li class="nav-item">
          <%=link_to "New Event", new_event_path,class:"nav-link active"%>
          </li>
        <li class="nav-item">
          <%=link_to "All Users", users_path,class:"nav-link"%>
        </li>
        <%end%>
        <li class="nav-item">
          <%=link_to "All Event", events_path,class:"nav-link"%>
        </li>
         <li class="nav-item">
          <%=link_to "Free Events", filter_path(:free),class:"nav-link"%>
        </li>
        <li class="nav-item">
          <%=link_to "Past Events", filter_path(:past),class:"nav-link"%>
        </li>
        
      </ul>
      <ul class="navbar-nav me-0">
      <%if current_user%>
        <li class="nav-item">
         <%=link_to current_user.name, current_user ,class:"nav-link"%>
        </li>
         <li class="nav-item">
          <%=link_to 'LOGOUT', session_path,method: :delete,class:"nav-link"%>
        </li>
        <%else%>
        <li class="nav-item">
          <%=link_to "SIGN UP", signup_path,class:"nav-link"%>
        </li>
        <li class="nav-item">
         <%=link_to "SIGN IN", new_session_path,class:"nav-link"%>
        </li>
      <%end%>
        <li class="nav-item">
          <%= link_to "Contact Us", new_contact_path, class:"nav-link"%>
        </li>
      </ul>
    </div>
  </div>
</nav>