config/routes.rb
Rails.application.routes.draw do
  resources :categories
  resources :events do 
    resources :likes
    resources :registrations
  end
  resources :contacts, only: [:new, :create]
  root to: 'events#index'
  get 'events/filter/:filter', to: 'events#index',as: :filter
  resources :users
  get 'signup', to: 'users#new'

  resource :session , only: [:new, :create, :destroy]
end

app/models/event.rb
class Event < ApplicationRecord
  extend FriendlyId
  friendly_id :name, use: :slugged
  
  validates :location, length: { minimum: 5, maximum: 100}
  validates :description, length: { minimum: 10, maximum: 600 }
  validates :price , presence: true
  validates :capacity , numericality: 
                        {only_integer: true, greater_than_or_equal_to: 0}
  validates :name,length: {minimum: 2 , maximum: 200}

  has_many :registrations, dependent: :destroy

  has_many :event_categories
  has_many :categories , through: :event_categories

  has_many :likes, dependent: :destroy
  has_many :likers, through: :likes ,source: :user


  def free?
    price == 0 || price == ''
  end

   def available_spot
      return(capacity - registrations.size)
   end

  def sold_out
    (capacity - registrations.size).zero? || registrations.map(&:user_id ).include?(likers)
  end

  
 

# Scopes
 scope :upcoming, -> {where("starts_at > ?", Time.now).order("starts_at")}
 scope :free, -> {upcoming.where(price: 0 ).order("name")}
 scope :past, -> {where("starts_at < ?", Time.now).order("starts_at desc")}
 scope :recent, -> (max=3){past.limit(max).order("starts_at")}
 scope :close_by, -> (similar_events){upcoming.where("location = ?",(similar_events)).order("starts_at")}
 
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user , except: [:index, :show]
  before_action :verify_admin, except:[:index, :show]
  before_action :set_events, only: [:show, :edit, :update, :destroy]
  def index
    case params[:filter] 
    when "past"
      @events = Event.past 
    when "free"
      @events = Event.free 
    when "recent"
      @events = Event.recent 
    else
      @events = Event.upcoming
    end
  end

  def new
    @event = Event.new
  end

  def create
    @event = Event.new(event_params)
    if @event.save
      redirect_to event_path(@event), notice: "Event Successfully created"
    else
      render :new
    end
  end

  def show
    @likers =@event.likers
    @near_by_events = Event.close_by(@event.location).excluding(@event)
    if current_user
      @like = current_user.likes.find_by(event_id: @event.id)
    end
  end

   def edit
     
   end

  def update
    if @event.update(event_params)
      redirect_to event_path(@event),notice: "Event Successfully Updated"
    else
      render :edit
    end
  end


  def destroy
    @event.destroy
    redirect_to events_path
  end

  private 

  def set_events
    @event = Event.friendly.find(params[:id])
  end

  def verify_ower
    if current_user && current_user.id != @event.id 
      redirect_to root_path alert: "Access denial! "
    end
  end

  def event_params
    params.require(:event).permit(:name, :location, :description, :price, :starts_at, :capacity, category_ids:[])
  end

end

app/helpers/events_helper.rb
module EventsHelper
 
end

app/views/events/_form.html.erb
 <%= form_with(model: event) do |f|%>

    <%=render 'shared/errors', object: event%>

  <div class="mb-3">

    <%=f.label :name,"Event name",class:"form-label"%>
    <%=f.text_field :name, class:"form-control"%>
  </div>

  <div class="mb-3">
    <%=f.label :description,"Event Description",class:"form-label"%>
    <%=f.text_area :description, class:"form-control"%>
  </div>

  <div class="mb-3">
    <%=f.label :location,"Event Location",class:"form-label"%>
    <%=f.text_field :location, class:"form-control"%>
  </div>

   <div class="mb-3">
    <%=f.label :price,"Event Price",class:"form-label"%>
    <%=f.number_field :price, class:"form-control"%>
  </div>

    <div class="mb-3">
    <%=f.label :capacity,"Event Spots",class:"form-label"%>
    <%=f.number_field :capacity, class:"form-control"%>
  </div>
  

  <div class="mb-3">
    <%=f.label :date_time,"Event Time",class:"form-label"%> <br>
    <%=f.datetime_select :starts_at, {ampm: true},class:"datetime"%>
  </div>

  <div class=" mb-3">
    <%=f.label :categories,class:"form-label"%> <br>
     <%=f.collection_check_boxes :category_ids, Category.all, :id, :name do |b|%> 
        <div class="form-check ">
          <%=b.label class: "form-check-label" do %> 
            <%=b.check_box class:"form-check-input"%>
            <%=b.text%>
          <%end%>
        </div>
     <%end%>
  </div>

  <div class="mb-3">
    <%=f.submit class:"btn btn-primary"%>
  </div>


  <%end%>

app/views/events/edit.html.erb
<div class="container">
 
  <h1> Editing <%= @event.name%></h1>
 <%= render 'form',event: @event%>
</div>

app/views/events/index.html.erb
<div class="container">
    <div class="row">
      <%@events.each do |event|%>
      <div class="col-3 my-3">
      <%=link_to event do%>
        <div class="card">
          <div class="card-body bg-light">
            <h5 class="card-title"><%=event.name%></h5>
            <h6 class="card-subtitle mb-2 text-muted"><%=event.location%></h6>
            <p class="card-text"> <%=event.description%> </p>
            <span class="card-link"><%=day_time(event)%></span>
            <span class="card-link"> Price: <%= price(event)%></span>
          </div>
            <div class="card-footer d-flex justify-content-between">
              <span>Number of Participants</span><span><%=event.registrations.size%></span>
            </div>
        </div>
        <%end%>
       </div>
       <%end%>
  </div>
  

app/views/events/new.html.erb
<div class="container">
    <h1>Create Event</h1>
    <%= render  'form', event: @event%>
</div>

app/views/events/show.html.erb
<div class="container my-5 d-flex bd-highlight">
  <div class="bd-highlight">

      <h1><%= @event.name%></h1>
      <%if current_user%>
        <div class="likes d-flex my-1">
          <%=like_or_unlike(@like, @event)%>
            <div class="px-2 bg-dark text-white">
              <%=@likers.size%>
            </div>
        </div>
      <%end%>
      <strong>price:</strong> <span class="badge rounded-pill bg-success"><%=price(@event)%></span> <br>
      <strong>Available Spots:</strong> <%=availability(@event)%>
      <div class="my-2">
        <%=@event.description%>
      </div>
        Location: <%=@event.location%> <br>
        Start: <%=day_time(@event)%>

  
      <div class="my-2">
        <%=event_sold_out(@event, current_user)%>
      </div>

         

        <div class="my-2">
          <%=link_to 'View All Registered Members', event_registrations_path(@event)%>
        </div>

        <% if current_user_admin?%>
          <div class="my-2 admin">
            <%=link_to 'Edit Edit Details', edit_event_path(@event), class:"btn btn-secondary btn-sm"%>
            <%=link_to 'Delete Event', event_path(@event), method: :delete, data:{confirm: "Are You Sure?"},class:"btn btn-danger btn-sm"%>
          </div>
        <%end%>
  </div>

  <div class="bd-highlight ms-4">
    <%if @likers.present?%>
      <h4>Follwers</h4>
      <ul class="list-group">
      <%@likers.each do |user|%>
      <li class="list-group-item">
          <%=link_to user.name,(user)%>
      </li>
      <%end%>
      </ul>
    <%end%>

    <div class="my-4">
      <% if @categories.present?%>
        <h5>Categories</h5>
        <ul class="list-group">
        <%@categories.each do |category| %>
          <li class="list-group-item">
            <%=category.name%>
          </li>
          <%end%>
        </ul>
      <%end%>
    </div>

  </div>

</div> 

<div class="container">

   <div class="my-5">
    <h1>Events Near By</h1>
      <ul>
    <%@near_by_events.each do |event|%>
        <li><%= link_to event.name, event %></li>
    <%end%>
      </ul>
   </div>
</div>